import video3 from "@/assets/videos/video-3.mp4";
import video2 from "@/assets/videos/video-2.mp4";
import video4 from "@/assets/videos/video-4.mp4";
import video1 from "@/assets/videos/video-1.mp4";
import video5 from "@/assets/videos/video-5.mp4";
import video6 from "@/assets/videos/video-6.mp4";
import video7 from "@/assets/videos/video-7.mp4";
import video8 from "@/assets/videos/video-8.mp4";
import video9 from "@/assets/videos/video-9.mp4";
import video10 from "@/assets/videos/video-10.mp4";
import video11 from "@/assets/videos/video-11.mp4";
import video12 from "@/assets/videos/video-12.mp4";

export const videos = [
    {
        id: 1,
        video: video3,
        fullName: 'Hello kitty!',
        nickName: 'le cong to',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        likeCount: "275.8K",
        commentCount: "814M",
        shareCount: "742K",
        bio: 'Lập trình thật dễ!!!',
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 2,
        video: video2,
        fullName: 'Vnua!!!',
        nickName: 'ZentSoft',
        likeCount: "36.7K",
        commentCount: "1540",
        shareCount: "161K",
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4797/63bbdcfc762e1.jpg',
        bio: 'Lập trình thật dễ!!!',
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 3,
        video: video4,
        fullName: 'Nguyễn vũ!',
        nickName: 'Vunguyencode',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/80b4fd9f5ad407f7e1e2c20ca17a2550~c5_100x100.jpeg?x-expires=1685016000&x-signature=XgUd9Cdysc95LuHjbRVuVROlTUk%3D',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "60K",
        commentCount: "591M",
        shareCount: "104K",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 4,
        video: video1,
        fullName: 'Duy Thẩm!',
        nickName: 'zukaaaaaa!!!',
        avatar: 'https://p9-sign-sg.tiktokcdn.com/aweme/100x100/tiktok-obj/1665757201241090.jpeg?x-expires=1685016000&x-signature=yqInOEWIROsn8%2FQUUko3x1j9IIA%3D',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "36.2K",
        commentCount: "424",
        shareCount: "157",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 5,
        video: video5,
        fullName: 'Kiều trinh!',
        nickName: 'Trinh Xuan An',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/b19272ccff7073ea4ed817931f19251f~c5_100x100.jpeg?x-expires=1685019600&x-signature=7EInc9FP2yqnbL%2BKxzaCm3fEaww%3D',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "48.6K",
        commentCount: "1622",
        shareCount: "254",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 6,
        video: video6,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/fb0c68381e0d6024d85bc51b3ad56fb9~c5_100x100.jpeg?x-expires=1685019600&x-signature=Y0K1DO8Lt5fuP9%2B148p8%2B7sQlXo%3D',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "59.4K",
        commentCount: "1623",
        shareCount: "6858",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 7,
        video: video7,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4138/636d2bee54644.jpg',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "64.5K",
        commentCount: "449",
        shareCount: "351",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 8,
        video: video8,
        fullName: 'Le Xuan Dai!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/3927/63da2f11ce330.jpg',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "73.7K",
        commentCount: "201",
        shareCount: "61",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 9,
        video: video9,
        fullName: 'Son Tung!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/5287/642c714f91301.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "80K",
        commentCount: "676",
        shareCount: "774",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 10,
        video: video10,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "12.1M",
        commentCount: "57K",
        shareCount: "261.5K",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 11,
        video: video11,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "54.8K",
        commentCount: "773",
        shareCount: "1609",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 12,
        video: video12,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "540.4K",
        commentCount: "7428",
        shareCount: "7674",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 13,
        video: video6,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "1.7M",
        commentCount: "6851",
        shareCount: "3158",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 14,
        video: video6,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "12.7K",
        commentCount: "379",
        shareCount: "79",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
    {
        id: 15,
        video: video6,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        bio: 'Lập trình thật dễ!!!',
        likeCount: "160.7K",
        commentCount: "1442",
        shareCount: "624",
        music: 'Every Single Thing - Homeshake',
        tick: true,
    },
];