import video3 from '@/assets/videos/video-3.mp4';
import video2 from '@/assets/videos/video-2.mp4';
import video4 from '@/assets/videos/video-4.mp4';
import video1 from '@/assets/videos/video-1.mp4';
import video5 from '@/assets/videos/video-5.mp4';
import video6 from '@/assets/videos/video-6.mp4';
import video7 from '@/assets/videos/video-7.mp4';
import video8 from '@/assets/videos/video-8.mp4';
import video9 from '@/assets/videos/video-9.mp4';
import video10 from '@/assets/videos/video-10.mp4';
import video11 from '@/assets/videos/video-11.mp4';
import video12 from '@/assets/videos/video-12.mp4';

export const listUser = [
    {
        id: 1,
        fullName: 'Hello kitty!',
        nickName: '🖤LeCongTo🖤',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4813/63f209de3947c.png',
        tick: true,
        video: {
            id: 1,
            video: video3,
            likeCount: '275.8K',
            commentCount: '814M',
            bookmarkCount: '2010',
            shareCount: '742K',
            bio: 'Kênh được lập ra để trả lời câu hỏi “Bố Tâm làm gì thế?” Các cậu cứ mạnh dạn hỏi kkk!',
            music: 'Kẻ Thật Lòng Phía Sau',
        },
    },
    {
        id: 2,
        fullName: 'Vnua!-IT-K66CNPMC',
        nickName: 'ZentSoft',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4797/63bbdcfc762e1.jpg',
        tick: false,
        video: {
            id: 2,
            video: video12,
            likeCount: '36.7K',
            commentCount: '1540',
            bookmarkCount: '2010',
            shareCount: '161K',
            bio: 'Bật mí thêm 8 Extensions trên VScode giúp bạn nâng trình hơn nè',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 3,
        fullName: 'Nguyễn vũ!',
        nickName: 'Vunguyencode',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/80b4fd9f5ad407f7e1e2c20ca17a2550~c5_100x100.jpeg?x-expires=1685016000&x-signature=XgUd9Cdysc95LuHjbRVuVROlTUk%3D',
        tick: true,
        video: {
            id: 3,
            video: video5,
            bio: 'Tính năng cực hay trong VSCode, bạn biết chưa?',
            likeCount: '60K',
            commentCount: '591M',
            bookmarkCount: '2010',
            shareCount: '104K',
            music: 'son original - 𝐖𝐒𝐇',
        },
    },
    {
        id: 4,
        fullName: 'Duy Thẩm!',
        nickName: 'zukaaaaaa!!!',
        avatar: 'https://p9-sign-sg.tiktokcdn.com/aweme/100x100/tiktok-obj/1665757201241090.jpeg?x-expires=1685016000&x-signature=yqInOEWIROsn8%2FQUUko3x1j9IIA%3D',
        tick: false,
        video: {
            id: 4,
            video: video1,
            bio: 'Những Shortcut thông dụng trong VS Code giúp thao tác nhanh và hiệu quả hơn! !',
            likeCount: '36.2K',
            commentCount: '424',
            bookmarkCount: '2010',
            shareCount: '157',
            music: 'nhạc nền - Maz Media Music',
        },
    },
    {
        id: 5,
        fullName: 'Kiều trinh!',
        nickName: 'Trinh Xuan An🖤',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/b19272ccff7073ea4ed817931f19251f~c5_100x100.jpeg?x-expires=1685019600&x-signature=7EInc9FP2yqnbL%2BKxzaCm3fEaww%3D',
        tick: true,
        video: {
            id: 5,
            video: video4,
            bio: 'Create diagrams right in VS Code with the Draw.io Integration extension!!',
            likeCount: '48.6K',
            commentCount: '1622',
            bookmarkCount: '2010',
            shareCount: '254',
            music: 'nhạc nền - Cao Thủ Liên Quân Official',
        },
    },
    {
        id: 6,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep▶️',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/fb0c68381e0d6024d85bc51b3ad56fb9~c5_100x100.jpeg?x-expires=1685019600&x-signature=Y0K1DO8Lt5fuP9%2B148p8%2B7sQlXo%3D',
        tick: false,
        video: {
            id: 6,
            video: video6,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '59.4K',
            commentCount: '1623',
            bookmarkCount: '2010',
            shareCount: '6858',
            music: 'nhạc nền - 𝐍𝐢𝐜𝐡𝐨𝐥𝐚𝐬𝐟𝐮𝐤𝐚',
        },
    },
    {
        id: 7,
        fullName: 'Sumggggg!',
        nickName: 'DuongTienDat',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4138/636d2bee54644.jpg',
        tick: true,
        video: {
            id: 7,
            video: video7,
            bio: 'Đăng bao giờ ae chán k xem nữa thì thoi🤣!',
            likeCount: '64.5K',
            commentCount: '449',
            bookmarkCount: '2010',
            shareCount: '351',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 8,
        fullName: 'Le Xuan Dai!',
        nickName: 'LeThiHien',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/3927/63da2f11ce330.jpg',
        tick: false,
        video: {
            id: 8,
            video: video8,
            bio: 'Của mình Thì Nhất định Phải Là Của Mình 😏!!',
            likeCount: '73.7K',
            commentCount: '201',
            bookmarkCount: '2010',
            shareCount: '61',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 9,
        fullName: 'Son Tung!',
        nickName: 'BuiThiNgocAnh',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/5287/642c714f91301.png',
        tick: true,
        video: {
            id: 9,
            video: video9,
            bio: 'One of the handiest new features of vscode… customize your setup with Profiles!!!',
            likeCount: '80K',
            commentCount: '676',
            bookmarkCount: '2010',
            shareCount: '774',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 10,
        fullName: 'NhanTammm!!',
        nickName: 'VuVanThuong',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/725be115c478adad12e9245e23511fb4~c5_100x100.jpeg?x-expires=1685260800&x-signature=hNixKd8XLi3BRiamas4EnO4ejNo%3D',
        tick: false,
        video: {
            id: 10,
            video: video10,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '12.1M',
            commentCount: '57K',
            bookmarkCount: '2010',
            shareCount: '261.5K',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 11,
        fullName: 'MeLapTRinh!',
        nickName: 'NgoCongThang',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/80085f20c5aba79a468d8028918c73ae~c5_100x100.jpeg?x-expires=1685260800&x-signature=I%2BsbuhrQ0OD3xjsuptI5sMIMBLE%3D',
        tick: true,
        video: {
            id: 11,
            video: video11,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '54.8K',
            commentCount: '773',
            bookmarkCount: '2010',
            shareCount: '1609',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 12,
        fullName: 'NguyenKInh!',
        nickName: 'PppVuPhuong🖤',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/2e647f85d943721a1bb1db46d7358f17~c5_100x100.jpeg?x-expires=1685260800&x-signature=nN1ZTDFvK5iUwxFX5GTFv5xU%2BRU%3D',
        tick: false,
        video: {
            id: 12,
            video: video2,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '540.4K',
            commentCount: '7428',
            bookmarkCount: '2010',
            shareCount: '7674',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 13,
        fullName: 'LeCongTHanh!',
        nickName: 'NgocPhong',
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tos-alisg-avt-0068/587f818a210d1e97a469349b09ebe238.jpeg?x-expires=1685260800&x-signature=jIkzdDJbAZxmkeyufC0Pm7qcK54%3D',
        tick: true,
        video: {
            id: 13,
            video: video6,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '1.7M',
            commentCount: '6851',
            bookmarkCount: '2010',
            shareCount: '3158',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 14,
        fullName: 'SonDUKU!',
        nickName: 'MinhHiep🖤',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/c897847e2477c35d335397539a1f918b~c5_100x100.jpeg?x-expires=1685264400&x-signature=8xZ2K09R3fB9csvP1mJGNOyek3A%3D',
        tick: true,
        video: {
            id: 14,
            video: video6,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '12.7K',
            commentCount: '379',
            bookmarkCount: '2010',
            shareCount: '79',
            music: 'Every Single Thing - Homeshake',
        },
    },
    {
        id: 15,
        fullName: 'Sumggggg!',
        nickName: 'Phan Cong Diep',
        avatar: 'https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-giso/f68a312ef26213fda69ec4342b4d6848~c5_100x100.jpeg?x-expires=1685264400&x-signature=bqF%2Fo8ra339YEacJcFnpBETwr%2BU%3D',
        tick: true,
        video: {
            id: 15,
            video: video6,
            bio: 'Lập trình thật dễ!!!',
            likeCount: '160.7K',
            commentCount: '1442',
            bookmarkCount: '2010',
            shareCount: '624',
            music: 'Every Single Thing - Homeshake',
        },
    },
];
